// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MitraSolusiTelematika.Repositories;

namespace MitraSolusiTelematika.Migrations
{
    [DbContext(typeof(MstDbContext))]
    partial class MstDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MitraSolusiTelematika.Models.KodePos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Jenis")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Kabupaten")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Kecamatan")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Kelurahan")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NoKodePos")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Propinsi")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("KodePos");
                });
#pragma warning restore 612, 618
        }
    }
}
